### ISSUE TITLE
Учтите замечания к предыдущму проекту

### ISSUE THREAD

**Issue by coursar** [rustamSurmashev/Run#1]
https://github.com/rustamSurmashev/homework_1/issues

**Comment by rustamSurmashev** [comment]
@coursar, данное ДЗ выполнено:
1. изменено название репозитория
2. использован хороший файл .гитигнор (который не игнорирует джейсоны)
3. добавлен файл run-app.js
4. добавлен Travis CI
5. добавлен CodeCov (100 %)

Сейчас займусь "причесыванием" остальных ДЗ.

**Comment by coursar** [comment]
Переименуйте html в index.html
